# Generated by Django 3.0.1 on 2019-12-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player Chance'), ('S', 'Second Player Chance'), ('W', 'First Player WINS'), ('L', 'Second Player WINS'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
